#!/bin/sh

docker stop `docker ps -a -q --filter="name=pulsar*"`

docker ps

rm -rf $PULSAR/data

docker run \
    --name pulsar-standalone  \
    -p 6650:6650 -p 8080:8080 \
    -d --rm \
    -v "$PULSAR"/connectors:/pulsar/connectors \
    -v "$PULSAR"/logs/functions:/tmp/functions \
    -v "$PULSAR"/data:/pulsar/data \
    -v "$PULSAR"/root:/root \
    -v "$PULSAR"/conf:/pulsar/conf \
    apachepulsar/pulsar-standalone

docker run -it \
    --name pulsar-manager \
    -p 9527:9527 \
    -d --rm \
    -e REDIRECT_HOST=127.0.0.1 \
    -e REDIRECT_PORT=9527 \
    -e DRIVER_CLASS_NAME=org.postgresql.Driver \
    -e URL='jdbc:postgresql://127.0.0.1:5432/pulsar_manager' \
    -e USERNAME=pulsar \
    -e PASSWORD=pulsar \
    -e LOG_LEVEL=DEBUG \
    -v "$PULSAR"/ui/data:/data \
    --link pulsar-standalone \
    apachepulsar/pulsar-manager:v0.1.0
